# Generated by Django 3.1.3 on 2020-11-23 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('contenido', models.CharField(max_length=200)),
                ('reccion', models.CharField(max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.autor')),
                ('idPub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.publication')),
            ],
        ),
    ]
