# Generated by Django 3.1.3 on 2020-11-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201123_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reccion',
        ),
        migrations.AddField(
            model_name='publication',
            name='reccion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
