# Generated by Django 3.1.3 on 2020-11-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_comment_idpub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='reccion',
            field=models.IntegerField(default=0),
        ),
    ]
